<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Password_Editing_Tool</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common Support\Common Support.csproj" />
    <ProjectReference Include="..\Console_Support\Console_Support.csproj" />
    <ProjectReference Include="..\Facade Support\Facade Support.csproj" />
    <ProjectReference Include="..\Obfuscation in Existing PNG\Obfuscation in Existing PNG.csproj" />
    <ProjectReference Include="..\Pad Based Encryption\Pad Based Encryption.csproj" />
  </ItemGroup>

</Project>
